name: 报告问题
description: 报告一个很明显的问题
body:
  - type: markdown
    attributes:
      value: |
        # 问题报告

        需要注意的是，您的问题此前可能已经被报告过。在报告问题之前，请先检查以下内容：
        - 置顶的 Issue, 位于 [Issue 列表](https://github.com/Game-Dev-Dep/Shittim_Canvas/issues) 的顶部。
        - 标签为 `priority:0` 且 Open 的 Issue， 可在 [这里](https://github.com/Game-Dev-Dep/Shittim_Canvas/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apriority%3A0) 查看。
        - 还有最重要的, 在 [Issues](https://github.com/Game-Dev-Dep/Shittim_Canvas/issues) 中搜索。如果发现您反馈的问题已存在，请在该 Issue 下提供可能有用的信息。

  - type: dropdown
    attributes:
      label: 问题类型
      description: 请选择最符合的问题类型。
      options:
        - 崩溃
        - 行为
        - 性能
        - 外观
        - 其他
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 您是怎么发现这个问题的？请尽可能详细的描述。
      placeholder: |
        例如：
        1. 打开软件
        2. 点击某处
        3. 出现什么问题
    validations:
      required: true

  - type: textarea
    attributes:
      label: 截图或录屏
      description: 添加截图或录屏可以帮助我们更快地定位问题。
      placeholder: 将 截图 / 录屏 拖拽到此处。
    validations:  
      required: false

  - type: input
    attributes:
      label: Windows 版本
      description: 请运行 `winver` 来获取您的 Windows 版本号。这可以帮助我们识别是否为 Windows 的特定版本问题。
      placeholder: 例如：Windows 10 版本 22H2

  - type: input
    attributes:
      label: 软件版本
      description: 您可以在软件的左上角找到

  - type: markdown
    attributes:
      value: |
        ## 日志

        我们建议您附加日志，这可以极大的帮助我们寻找问题。 见下文来了解如何获取日志。

        ### 获取日志

        1. 按 `Win + R` 键打开运行窗口。
        2. 输入 `%HOMEPATH%\AppData\LocalLow\Ivaldi Forge\Shittim Canvas`，并按回车键。
        3. 拖放 `.log` 文件到下面的日志部分。

  - type: textarea
    attributes:
      label: 日志
      placeholder: 拖拽日志到此处。
    validations:
      required: false
